"""Initial migration

Revision ID: 7b8c8514f31f
Revises: 
Create Date: 2024-09-17 13:49:19.204870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b8c8514f31f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "item_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("triangle_size", sa.Integer(), nullable=False),
        sa.Column("triangle_color", sa.String(), nullable=False),
        sa.Column("circle_size", sa.Integer(), nullable=False),
        sa.Column("circle_color", sa.String(), nullable=False),
        sa.Column("time_visible_ms", sa.Integer(), nullable=False),
        sa.Column("orientation", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_config_id"), "item_config", ["id"], unique=False)
    op.create_table(
        "test_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_config_id"), "test_config", ["id"], unique=False)
    op.create_table(
        "item_config_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("item_config_id", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("reaction_time_ms", sa.Integer(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_config_id"],
            ["item_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_config_result_id"), "item_config_result", ["id"], unique=False
    )
    op.create_table(
        "test_config_item_config",
        sa.Column("test_config_id", sa.Integer(), nullable=False),
        sa.Column("item_config_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_config_id"],
            ["item_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_config_id"],
            ["test_config.id"],
        ),
        sa.PrimaryKeyConstraint("test_config_id", "item_config_id"),
    )
    op.create_table(
        "test_config_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("test_config_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("wrong_answers", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_config_id"],
            ["test_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_config_result_id"), "test_config_result", ["id"], unique=False
    )
    op.create_table(
        "test_config_result_item_config_result",
        sa.Column("test_config_result_id", sa.Integer(), nullable=False),
        sa.Column("item_config_result_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_config_result_id"],
            ["item_config_result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_config_result_id"],
            ["test_config_result.id"],
        ),
        sa.PrimaryKeyConstraint("test_config_result_id", "item_config_result_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_config_result_item_config_result")
    op.drop_index(op.f("ix_test_config_result_id"), table_name="test_config_result")
    op.drop_table("test_config_result")
    op.drop_table("test_config_item_config")
    op.drop_index(op.f("ix_item_config_result_id"), table_name="item_config_result")
    op.drop_table("item_config_result")
    op.drop_index(op.f("ix_test_config_id"), table_name="test_config")
    op.drop_table("test_config")
    op.drop_index(op.f("ix_item_config_id"), table_name="item_config")
    op.drop_table("item_config")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
