name: Run Pytest with Alembic Migrations and Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10.14
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.14"

      # Set SECRET_KEY from GitHub secrets
      - name: Set environment variables
        run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      # Run Alembic migrations
      - name: Run Alembic Migrations
        run: |
          alembic -x seed_data=true upgrade head

      # Run Pytest and generate coverage report
      - name: Run tests with coverage
        run: |
          coverage run -m pytest --cov=backend backend/tests/
